### ISSUE TITLE
Misleading description

### ISSUE THREAD

**Issue by jesta88** [librg/librg#5]
Librg is advertised as an MMO solution but authoritative servers, while possible, seem like an afterthought and I don't see any API for interest management. In fact I would say that librg is ideal for *anything* besides MMO. 

Am I missing something obvious here?

**Comment by inlife** [comment]
Hello @jesta88!

Firstly, while we do agree an MMO title might be misleading for project like this, we do offer utilities and helpers that help us reduce bandwidth and performance costs by making sure each and every player receives only the data he is interested in. We make sure we send data to clients only about those entities that are "visible" and that are "close" based on their specific range settings. For example, distant player outside of city will not receive information about player/entities inside the city, because the city is not covered by his streaming range.

Secondly, we also offer an ability to send messages to all entities inside of a particular entity's interest range. There is no ability to send messages within a specific range based off of a random point in the world yet, however we are planning on adding it later on.

On the other hand, while we can say that the server authoritative model wasn't truly a priority while creating this library, if you look on it from the other side, it mostly requires sending needed inputs via messages from the client side and handling the game logic on the server side to make it work.

At last, the library itself was tested in an environment with more than thousand connected active player which, in some way, or according to some definitions, might be at least partially qualified as an MMO solution.

Nevertheless, we do value your opinion and we are going to try to update the description to make sure it represents the idea better and be less confusing.

If you have any more questions we will be glad to answer them.
Thank you!

**Comment by inlife** [comment]
@jesta88 just wanted to notify you, that we've updated the description.
have a nice day!
