### ISSUE TITLE
librg_network_stop on server doesn't trigger disconnect event on clients

### ISSUE THREAD

**Issue by eddiejames** [librg/librg#9]
Hello,

I could be missing something, but when I shutdown my server, none of the connected clients receive any event; they all just timeout. Looking at librg_network_stop, there doesn't appear to be anything to handle currently connected clients. They just get deleted with the zpl table.

Would be happy to contribute here, but not sure if I am missing something.

Thanks.

**Comment by zaklaus** [comment]
Hi eddiejames,
you're right, `librg_network_stop` doesn't notify clients about the event. This indeed should be fixed and handled properly. It will get attention eventually, but any contribution would be greatly appreciated.

Thanks for the info.

**Comment by bullno1** [comment]
I think this is tricky because in order to ensure that clients are actually notified about server shutdown, the service loop needs to be run. This makes librg_network_stop block which might not be desirable.

Should it have something like a "grace time" parameter which specifies how long to wait until it will just let clients timeout?

Alternatively, the API can be split into "stop" (tell clients to quit) vs "destroy" (release resources) but how would one handle "finish stopping" event?

**Comment by inlife** [comment]
@bullno1 actually very good point

I also have alternative suggestion, very similar to "grace time" parameter. Instead of waiting arbitrary time to "guess" that we sent all needed packets, we can just iterate peers calling disconnect on each, and then call enet_host_service in a while loop, till it returning result > 0, to pump out all and send yet unsent packets, and ignore any incoming packets.

As soon as all packets will be sent, the queue will be empty, and we can exit. Since librg_network_stop is already blocking on the client side (100ms delay), we might just choose this way since it doesn't really change anything around too much.

**Comment by zaklaus** [comment]
@inlife this could very well solve the issue indeed. Unless a better approach is proposed, we should stick to this solution.

**Comment by bullno1** [comment]
@inlife how would it behave if client for some reason is not acknowledging the packets? I guess enet will know to remove it from queue right?

**Comment by inlife** [comment]
fixed in https://github.com/librg/librg/commit/6f004c7dbc7075d8ee97089291f702bb93c3b296 and https://github.com/librg/librg/commit/3ca68ad0379eb5b424485f83c150731f9b49f3c9
